name: pgrkam
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to 

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_downloader: ^1.11.2
  text_scroll: ^0.2.0
  firebase_core: ^2.16.0
  firebase_auth: ^4.10.0
  cloud_firestore: ^4.9.2
  provider: ^6.0.5
  file_picker: ^5.5.0
  firebase_storage: ^11.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/fonts/HelveticaNeue.otf
        - asset: assets/fonts/HelveticaNeueBold.otf
        - asset: assets/fonts/HelveticaNeueMedium.otf
        - asset: assets/fonts/HelveticaNeueThin.otf